In [3]:
#Exercice1
import numpy as np

array=np.random.rand(5,5)
print("min=",array.min(), "max=",array.max())


min= 0.03308426875260173 max= 0.9762634900631563


In [5]:
#Exercise2 (normalisation)
array=np.random.rand(3,3)
array = (array - array.mean(axis=0)) / array.std(axis=0)
print(array)

[[ 0.7617428   0.62156091 -0.77662206]
 [-1.41276816 -1.41089251 -0.63523361]
 [ 0.65102537  0.7893316   1.41185567]]


In [11]:
#Exercise3

array1=np.arange(1,10.2,0.2)
print(array1)

[ 1.   1.2  1.4  1.6  1.8  2.   2.2  2.4  2.6  2.8  3.   3.2  3.4  3.6
  3.8  4.   4.2  4.4  4.6  4.8  5.   5.2  5.4  5.6  5.8  6.   6.2  6.4
  6.6  6.8  7.   7.2  7.4  7.6  7.8  8.   8.2  8.4  8.6  8.8  9.   9.2
  9.4  9.6  9.8 10. ]


In [13]:
#Exercise4

array1=np.random.rand(5,3)
array2=np.random.rand(3,2)
result=np.dot(array1,array2)
print(result)


[[1.05034892 0.99723533]
 [0.90689031 0.93096743]
 [2.16001613 2.07019636]
 [1.2252577  1.04922929]
 [0.5657767  0.49282586]]


In [20]:
#Exercise5

# Creating two matrices
A = np.array([[1, 2], [3, 4], [5, 6]])
B = np.array([[5, 6], [7, 8]])


result =A@B  

print("Matrix A:", A)
print("Matrix B:", B)
print("Matrix Multiplication Result:", result)


Matrix A: [[1 2]
 [3 4]
 [5 6]]
Matrix B: [[5 6]
 [7 8]]
Matrix Multiplication Result: [[19 22]
 [43 50]
 [67 78]]
