In [2]:
#Exercise1

import numpy as np

array=np.arange(10)
print(array)

[0 1 2 3 4 5 6 7 8 9]


In [4]:
#Exercise2

list=[3.14, 2.17, 0, 1, 2]
array=np.array(list, dtype=int)
print(array)


[3 2 0 1 2]


In [9]:
#Exercise3

array=np.arange(1,10)
array=array.reshape(3,3)
print(array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [10]:
#Exercise4

array=np.random.rand(4,5)
print(array)

[[0.22631826 0.60006417 0.008665   0.07382899 0.65467505]
 [0.08109367 0.06123715 0.23617238 0.28121997 0.73360519]
 [0.10812122 0.22192143 0.73809893 0.73679656 0.57088958]
 [0.09454386 0.66620777 0.66200886 0.94415182 0.42087272]]


In [12]:
#Exercise5

array = np.array([[21,22,23,22,22],[20, 21, 22, 23, 24],[21,22,23,22,22]])

print(array[1,:])

[20 21 22 23 24]


In [14]:
#Exercise6

array=np.arange(0,10)
array=array[::-1]
print(array)

[9 8 7 6 5 4 3 2 1 0]


In [15]:
#Exercise7(Matrix identity)

array=np.eye(4)
print(array)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [16]:
#Exercise8

array=np.array([1,2,3,4,5])
print("sum=",array.sum(), "Average=",array.mean())



sum= 15 Average= 3.0


In [17]:
#Exercise9

array=np.arange(1,21)
array=array.reshape(4,5)
print(array)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [18]:
#Exercise10

array=np.arange(1,10)
print(array[array%2==1])

[1 3 5 7 9]
